
export enum AventusType {
    Component,
    Lib,
    Data,
    RAM,
    Static,
    Definition,
    Unknow
}
export const AventusLanguageId = {
    Base: "Aventus",
    TypeScript: "Aventus Ts",
    HTML: "Aventus HTML",
    SCSS: "Aventus SCSS",
    WebComponent: "Aventus WebComponent",
    Package: "Aventus Ts",
    I18n: "Aventus I18n"

}
export const AventusExtension = {
    Base: ".avt",
    Config: "aventus.conf.avt",
    CsharpConfig: "aventus.sharp.avt",
    PhpConfig: "aventus.php.avt",
    ComponentLogic: ".wcl.avt",
    ComponentView: ".wcv.avt",
    ComponentStyle: ".wcs.avt",
    Component: ".wc.avt",
    GlobalStyle: ".gs.avt",
    Data: ".data.avt",
    Lib: ".lib.avt",
    RAM: ".ram.avt",
    State: ".state.avt",
    Static: ".static.avt",
    Definition: ".def.avt",
    DefinitionNpm: ".defnpm.avt",
    Template: "template.avt.ts",
    ConfigTemplate: "!aventus.conf.avt",
    Package: ".package.avt",
    I18n: ".i18n.avt",
} as const;

export enum AventusErrorCode {
    Unknow = 1000,
    ConfigJsonError,
    NoWebComponent,
    MultipleWebComponent,
    TagLower,
    AttributeLower,
    MissingVariable,
    ParsingParentFailed,
    OutsideInterpolation,
    UsedKeyword,
    MissingAttributeForLoop,
    MissingViewElement,
    viewElementNotFound,
    MissingInit,
    MissingProp,
    MissingWatchable,
    WrongTypeDefinition,
    MissingExtension,
    MissingImplementation,
    MissingMethod,
    FunctionNotAllowed,
    VariableNotAllowed,
    MissingFullName,
    SameNameFound,
    ConvertionImpossible,
    ExclamationMarkMissing,
    QuestionMarkMissing,
}