import { execFile as _execFile } from 'child_process';
import { resolve, join } from 'path';
import { promisify } from 'util';
import { GenericServer } from './GenericServer';


const execFile = promisify(_execFile);


export async function initEnvironnment(extensionPath: string) {
	try {
		installEnvironment({
			binPath: join(extensionPath, "lib", "bin"),
			variableName: 'AVENTUS_BIN'
		})
	} catch (e) {
		GenericServer.error(e);
	}
}

interface InstallEnvironmentOptions {
	variableName: string;
	binPath: string;
}

async function installEnvironment(
	options: InstallEnvironmentOptions
): Promise<void> {
	const variableName = validateVariableName(options.variableName);
	const binPath = resolve(options.binPath);

	switch (process.platform) {
		case 'win32':
			await installWindowsEnvironment(variableName, binPath);
			return;

		case 'linux':
		case 'darwin':
			await installUnixEnvironment(variableName, binPath);
			return;

		default:
			throw new Error(
				`Device not allowed : ${process.platform}`
			);
	}
}

async function installWindowsEnvironment(
	variableName: string,
	binPath: string,
): Promise<void> {
	const script = String.raw`
$ErrorActionPreference = 'Stop'

$variableName = $env:AVENTUS_VARIABLE_NAME
$binPath = $env:AVENTUS_BIN_PATH
$target = [System.EnvironmentVariableTarget]::User

# Récupère l'ancienne valeur avant toute modification.
$oldBinPath = [System.Environment]::GetEnvironmentVariable(
    $variableName,
    $target
)

# Si la variable contient déjà le bon chemin, aucune modification.
if (
    -not [string]::IsNullOrWhiteSpace($oldBinPath) -and
    $oldBinPath.TrimEnd('\', '/') -ieq $binPath.TrimEnd('\', '/')
) {
    exit 0
}

$currentPath = [System.Environment]::GetEnvironmentVariable(
    'Path',
    $target
)

if ($null -eq $currentPath) {
    $currentPath = ''
}

$entries = @(
    $currentPath -split ';' |
    ForEach-Object { $_.Trim() } |
    Where-Object { $_ -ne '' }
)

$newEntries = [System.Collections.Generic.List[string]]::new()
$newBinPathAlreadyPresent = $false

foreach ($entry in $entries) {
    $normalizedEntry = $entry.TrimEnd('\', '/')

    # Supprime l'ancienne valeur complète de AVENTUS_BIN du Path.
    if (
        -not [string]::IsNullOrWhiteSpace($oldBinPath) -and
        $normalizedEntry -ieq $oldBinPath.TrimEnd('\', '/')
    ) {
        continue
    }

    # Supprime aussi une éventuelle ancienne référence %AVENTUS_BIN%.
    $variableReference = '%' + $variableName + '%'

    if (
        $normalizedEntry -ieq $variableReference.TrimEnd('\', '/')
    ) {
        continue
    }

    # Évite d'ajouter le nouveau chemin plusieurs fois.
    if (
        $normalizedEntry -ieq $binPath.TrimEnd('\', '/')
    ) {
        if (-not $newBinPathAlreadyPresent) {
            $newEntries.Add($entry)
            $newBinPathAlreadyPresent = $true
        }

        continue
    }

    $newEntries.Add($entry)
}

# Ajoute le nouveau chemin complet s'il n'existe pas.
if (-not $newBinPathAlreadyPresent) {
    $newEntries.Add($binPath)
}

$newPath = $newEntries -join ';'

# Met à jour la variable et le Path seulement après avoir traité l'ancienne valeur.
[System.Environment]::SetEnvironmentVariable(
    $variableName,
    $binPath,
    $target
)

[System.Environment]::SetEnvironmentVariable(
    'Path',
    $newPath,
    $target
)
`;

	const powershell =
		process.env.SystemRoot
			? join(
				process.env.SystemRoot,
				'System32',
				'WindowsPowerShell',
				'v1.0',
				'powershell.exe'
			)
			: 'powershell.exe';

	try {
		await execFile(
			powershell,
			[
				'-NoLogo',
				'-NoProfile',
				'-NonInteractive',
				'-ExecutionPolicy',
				'Bypass',
				'-Command',
				script
			],
			{
				windowsHide: true,
				env: {
					...process.env,
					AVENTUS_VARIABLE_NAME: variableName,
					AVENTUS_BIN_PATH: binPath,
				},
				maxBuffer: 1024 * 1024
			}
		);
	} catch (error) {
		throw new Error(
			`Impossible to edit user variables : ${getErrorMessage(error)}`,
			{ cause: error }
		);
	}
}

async function installUnixEnvironment(
	variableName: string,
	binPath: string,
): Promise<void> {
	const home = process.env.HOME;

	if (!home) {
		throw new Error(
			'Can\'t determine the user folder.'
		);
	}

	const fs = await import('node:fs/promises');

	/*
	 * On utilise un fichier dédié, puis on le charge depuis le fichier
	 * de configuration du shell.
	 */
	const environmentFile = join(home, '.aventus-env');

	const escapedBinPath = escapeShellSingleQuotedString(binPath);

	const environmentContent = [
		'# Generated by the Aventus VS Code extension.',
		`export ${variableName}='${escapedBinPath}'`,
		`case ":$PATH:" in`,
		`    *":$${variableName}:"*) ;;`,
		`    *) export PATH="$${variableName}:$PATH" ;;`,
		`esac`,
		''
	].join('\n');

	await fs.writeFile(environmentFile, environmentContent, {
		encoding: 'utf8',
		mode: 0o600
	});

	const shellConfigurationFiles = getUnixShellConfigurationFiles(home);

	for (const configurationFile of shellConfigurationFiles) {
		await ensureUnixEnvironmentFileLoaded(
			configurationFile,
			environmentFile
		);
	}
}

function getUnixShellConfigurationFiles(home: string): string[] {
	const shell = process.env.SHELL ?? '';

	if (shell.endsWith('/zsh')) {
		return [join(home, '.zshrc')];
	}

	if (shell.endsWith('/bash')) {
		return [join(home, '.bashrc')];
	}

	if (shell.endsWith('/fish')) {
		throw new Error(
			'Fish utilise une syntaxe différente. ' +
			'Une installation spécifique à Fish doit être implémentée.'
		);
	}

	// Fallback POSIX courant.
	return [join(home, '.profile')];
}

async function ensureUnixEnvironmentFileLoaded(
	configurationFile: string,
	environmentFile: string
): Promise<void> {
	const fs = await import('node:fs/promises');

	const markerStart = '# >>> Aventus environment >>>';
	const markerEnd = '# <<< Aventus environment <<<';

	const escapedFile = escapeShellSingleQuotedString(environmentFile);

	const block = [
		markerStart,
		`if [ -f '${escapedFile}' ]; then`,
		`    . '${escapedFile}'`,
		'fi',
		markerEnd
	].join('\n');

	let content = '';

	try {
		content = await fs.readFile(configurationFile, 'utf8');
	} catch (error) {
		const nodeError = error as NodeJS.ErrnoException;

		if (nodeError.code !== 'ENOENT') {
			throw error;
		}
	}

	const blockRegex = new RegExp(
		`${escapeRegExp(markerStart)}[\\s\\S]*?${escapeRegExp(markerEnd)}`,
		'm'
	);

	if (blockRegex.test(content)) {
		content = content.replace(blockRegex, block);
	} else {
		content = `${content.trimEnd()}\n\n${block}\n`;
	}

	await fs.writeFile(configurationFile, content, 'utf8');
}

function validateVariableName(variableName: string): string {
	if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(variableName)) {
		throw new Error(
			`Invalid variable name : ${variableName}`
		);
	}

	return variableName;
}

function escapeShellSingleQuotedString(value: string): string {
	return value.replace(/'/g, `'\\''`);
}

function escapeRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function getErrorMessage(error: unknown): string {
	if (error instanceof Error) {
		return error.message;
	}

	return String(error);
}